language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode11
    env:
    - JOB="MacOS"
  - os: linux
    env:
    - JOB="Linux"
    dist: trusty
script:
- export SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2019-07-01-a
- git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
- export SWIFTENV_ROOT="$HOME/.swiftenv"
- export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
- swiftenv install $SWIFT_VERSION
- swiftenv rehash
- swift run -c release tests
